# Generated by Django 5.0.1 on 2024-01-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0037_alter_registration_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_code',
        ),
        migrations.AddField(
            model_name='offeredsubject',
            name='class_code',
            field=models.CharField(default=5413, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='staff_id',
            field=models.CharField(max_length=9),
        ),
    ]
